name: hate_speech_classification
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hive: ^2.2.2
  path_provider: ^2.0.11
  snowball_stemmer: ^0.1.0
  stacked: ^2.3.12
  stacked_services: ^0.8.26

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.7.9+1

flutter:
  uses-material-design: true
  assets:
    - assets/data/data.json
    - assets/data/dataset.json
    - assets/data/stopwords.json
  fonts:
    - family: YanoneKaffeesatz
      fonts:
        - asset: assets/fonts/YanoneKaffeesatz-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/YanoneKaffeesatz-Light.ttf
          weight: 300
        - asset: assets/fonts/YanoneKaffeesatz-Regular.ttf
          weight: 400
        - asset: assets/fonts/YanoneKaffeesatz-Medium.ttf
          weight: 500
        - asset: assets/fonts/YanoneKaffeesatz-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/YanoneKaffeesatz-Bold.ttf
          weight: 700
